Update main.yml
added integration tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -303,3 +303,31 @@ jobs:
           openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
         run: |
           oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch
+
+      - name: Run Integration Tests
+        env:
+          TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
+          BASIC_AUTH_USER: ${{secrets.BASIC_AUTH_USER}}
+          BASIC_AUTH_PASS: ${{secrets.BASIC_AUTH_PASS}}
+        run: |
+          RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
+          if [ "$RET" = "application/zip" ]; then
+          echo "Status: Failed Integration Test(s) found!"
+          exit 1
+          fi
+          if [[ "$RET" == *"json"* ]]; then
+          echo "Status: All Tests Passed"
+          fi
+          if [ "$RET" != "application/zip" ] && [[ "$RET" != *"json"* ]]; then
+          echo "Received content_type is $RET, was expecting json or zip"
+          exit 1
+          fi
+
+          - name: Archive production artifacts
+            uses: actions/upload-artifact@v2
+            if: failure()
+            with:
+              name: integration-tests-report
+              path: |
+                TestErrors.zip
+              retention-days: 5
